-- CreateTable
CREATE TABLE "Achievement" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "uid" INTEGER NOT NULL,
    "id_user" INTEGER NOT NULL,
    "crdate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Achievement_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Analyzer" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "buying" INTEGER NOT NULL DEFAULT 0,
    "quest" INTEGER NOT NULL DEFAULT 0,
    "underwear" INTEGER NOT NULL DEFAULT 0,
    "convert_mo" INTEGER NOT NULL DEFAULT 0,
    "beer" INTEGER NOT NULL DEFAULT 0,
    "beer_premiun" INTEGER NOT NULL DEFAULT 0,
    "birthday" INTEGER NOT NULL DEFAULT 0,
    "gold_lost" INTEGER NOT NULL DEFAULT 0,
    "gold_got" INTEGER NOT NULL DEFAULT 65,
    "xp_got" INTEGER NOT NULL DEFAULT 0,
    "xp_lost" INTEGER NOT NULL DEFAULT 0,
    "id_user" INTEGER NOT NULL,
    "crdate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Analyzer_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
